// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';
import { capacitorStorageAdapter } from './storage-adapter';

const SUPABASE_URL = "https://wiyfcvypeifbdaqnfgrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeWZjdnlwZWlmYmRhcW5mZ3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDEyNDYsImV4cCI6MjA3NTM3NzI0Nn0._xA81aVu_on-OL-axvskm4aCCywkIZliIiXGFu4ey2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use Capacitor storage for mobile, localStorage for web
const storage = Capacitor.isNativePlatform() ? capacitorStorageAdapter : localStorage;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: storage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});